export enum StationServices {
  dock,
  autodock = "autodock",
  blackmarket = "blackmarket",
  commodities = "commodities",
  contacts = "contacts",
  exploration = "exploration",
  initiatives = "initiatives",
  missions = "missions",
  outfitting = "outfitting",
  crewLounge = "crewlounge",
  rearm = "rearm",
  refuel = "refuel",
  repair = "repair",
  shipyard = "shipyard",
  tuning = "tuning",
  workshop = "workshop",
  missionsGenerated = "missionsgenerated",
  facilitator = "facilitator",
  research = "research",
  flightController = "flightcontroller",
  stationOperations = "stationoperations",
  onDockMission = "ondockmission",
  powerplay = "powerplay",
  searchAndRescue = "searchandrescue",
  shop = "shop",
  carrierManagement = "carriermanagement",
  carrierFuel = "carrierfuel",
  carrierVendor = "carriervendor",
  livery = "livery",
  modulePacks = "modulepacks",
  voucherRedemption = "voucherredemption",
  stationMenu = "stationMenu",
}
