export enum StationServices {
    dock,
    autodock = "Autodock",
    blackMarket = "BlackMarket",
    commodities = "Commodities",
    contacts = "Contacts",
    exploration = "Exploration",
    initiatives = "Initiatives",
    missions = "Missions",
    outfitting = "Outfitting",
    crewLounge = "CrewLounge",
    rearm = "Rearm",
    refuel = "Refuel",
    repair = "Repair",
    shipyard = "Shipyard",
    tuning = "Tuning",
    workshop = "Workshop",
    missionsGenerated = "MissionsGenerated",
    facilitator = "Facilitator",
    research = "Research",
    flightController = "FlightController",
    stationOperations = "StationOperations",
    onDockMission = "OnDockMission",
    powerplay = "Powerplay",
    searchAndRescue = "SearchAndRescue",
    shop = "Shop",
    carriermanagement = "CarrierManagement",
    carrierfuel = "CarrierFuel",
    voucherredemption = "VoucherRedemption",
    carriervendor = "CarrierVendor",
    modulepacks = "ModulePacks"
}
