export enum MusicTrackNames {
    noTrack = "NoTrack", 
    mainMenu = "MainMenu", 
    cQCMenu = "CQCMenu", 
    systemMap = "SystemMap", 
    galaxyMap = "GalaxyMap", 
    galacticPowers ="GalacticPowers",
    cQC = "CQC", 
    destinationFromHyperspace = "DestinationFromHyperspace", 
    destinationFromSupercruise = "DestinationFromSupercruise", 
    supercruise = "Supercruise", 
    combat_Unknown ="Combat_Unknown",
    unknown_Encounter = "Unknown_Encounter", 
    capitalShip = "CapitalShip", 
    combatLargeDogFight = "CombatLargeDogFight", 
    combat_Dogfight = "Combat_Dogfight", 
    combat_SRV ="Combat_SRV",
    unknown_Settlement = "Unknown_Settlement", 
    dockingComputer = "DockingComputer", 
    starport = "Starport", 
    unknown_Exploration = "Unknown_Exploration", 
    exploration ="Exploration",
}